networks:
  symc-network:
    driver: bridge

volumes:
  shareyourmusic:
    driver: local

services:
  mongo:
    container_name: symc-mongo
    image: mongo:8
    restart: always
    env_file: .env
    ports:
      - 7655:27017
    networks:
      - symc-network
    volumes:
      - shareyourmusic:/data/db

  mongo-express:
    container_name: symc-me
    image: mongo-express
    restart: always
    env_file: .env
    ports:
      - 3001:3435
    networks:
      - symc-network
    depends_on:
      - mongo
